version: '3.8'
services:
  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=median-db
    volumes:
      - ./db/:/var/lib/postgresql/data
    ports:
      - '5432:5432'

 